"use client";

import React from "react";
import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="min-h-screen pt-20" style={{ background: "var(--bg)" }}>
      <div className="mx-auto max-w-4xl px-6 py-24">
        <h1 className="text-4xl md:text-6xl font-black mb-8" style={{ color: "var(--text)" }}>
          Terms of Service
        </h1>
        <p className="text-sm text-slate-500 mb-12 uppercase tracking-widest font-bold">
          Last Updated: April 26, 2026 · Effective Immediately
        </p>

        <div className="space-y-10 text-slate-400 leading-relaxed">

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing or using ElectiQ (&quot;Service,&quot; &quot;Platform,&quot; &quot;we,&quot; &quot;our&quot;), you agree to be bound by these Terms of Service and all applicable laws and regulations of the Republic of India, including the <strong>Information Technology Act, 2000</strong>, the <strong>Digital Personal Data Protection Act, 2023 (DPDP Act)</strong>, and the <strong>Representation of the People Act, 1951</strong>. If you do not agree to these terms, you may not use this platform.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">2. Description of Service</h2>
            <p>
              ElectiQ is a non-partisan, AI-powered electoral education platform designed to assist Indian citizens with:
            </p>
            <ul className="list-disc pl-6 space-y-2 mt-4">
              <li>Voter registration guidance, polling booth discovery, and ECI procedure information.</li>
              <li>Fact-checking and verification of election-related claims via the Myth Buster tool.</li>
              <li>Generation of AI-powered infographics for educational purposes.</li>
              <li>Conversational assistance through the Voti AI Assistant.</li>
            </ul>
            <p className="mt-4">
              ElectiQ is strictly a <strong>citizen-education tool</strong> and is not affiliated with any political party, candidate, or electoral authority.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">3. Permitted Use</h2>
            <p>You may use ElectiQ solely for lawful, non-commercial, personal educational purposes. You agree <strong>not</strong> to:</p>
            <ul className="list-disc pl-6 space-y-2 mt-4">
              <li>Use the platform to spread electoral misinformation or propaganda.</li>
              <li>Scrape, copy, or reproduce content for commercial redistribution without written consent.</li>
              <li>Attempt to reverse-engineer, disrupt, or compromise the security of the Service.</li>
              <li>Use the Voti Assistant to generate political advertising or voter suppression content.</li>
              <li>Submit any false, misleading, or defamatory content through any input field.</li>
              <li>Violate the Model Code of Conduct (MCC) issued by the Election Commission of India.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">4. AI-Generated Content Disclaimer</h2>
            <p>
              All content generated by Voti Assistant and the Visual AI Engine is produced by artificial intelligence and is provided <strong>for informational purposes only</strong>. ElectiQ makes no warranty, express or implied, regarding the accuracy, completeness, or reliability of AI-generated content.
            </p>
            <p className="mt-4">
              Users are strongly advised to verify all electoral information against official sources, including the <strong>Election Commission of India (ECI)</strong> at <a href="https://voters.eci.gov.in" target="_blank" rel="noopener noreferrer" className="text-[#FF9933] underline">voters.eci.gov.in</a> and the <strong>National Voter&apos;s Service Portal</strong>. In case of any discrepancy, official ECI publications shall prevail.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">5. Intellectual Property</h2>
            <p>
              All source code, design assets, brand identity (including the ElectiQ name and logo), and written content on this platform are the intellectual property of ElectiQ and are protected under Indian copyright law. You may share links to this platform but may not reproduce or distribute our proprietary content without express written permission.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">6. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by applicable Indian law, ElectiQ and its operators shall not be liable for any direct, indirect, incidental, consequential, or punitive damages arising from your use of or inability to use the Service, including reliance on any AI-generated content for actual electoral decisions.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">7. Third-Party Services</h2>
            <p>
              ElectiQ integrates with Google Cloud AI services (Vertex AI, Gemini API, Text-to-Speech) and the Election Commission of India&apos;s public data endpoints. Use of these integrations is subject to the respective providers&apos; terms of service. ElectiQ is not responsible for any outages, errors, or data inaccuracies originating from third-party services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">8. Governing Law & Dispute Resolution</h2>
            <p>
              These Terms of Service shall be governed by and construed in accordance with the laws of the Republic of India. Any disputes arising under these terms shall be subject to the exclusive jurisdiction of the courts of New Delhi, India.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">9. Modifications to Terms</h2>
            <p>
              ElectiQ reserves the right to update these Terms of Service at any time. The &quot;Last Updated&quot; date at the top of this page will reflect the most recent changes. Continued use of the Service after any modification constitutes your acceptance of the revised terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">10. Contact</h2>
            <p>
              For any questions regarding these Terms of Service, please contact us at:<br />
              <strong>Email:</strong> legal@electiq.in<br />
              <strong>Address:</strong> ElectiQ Legal Division, New Delhi — 110001, India.
            </p>
          </section>

          <div className="mt-16 pt-8 border-t flex gap-6 flex-wrap" style={{ borderColor: "var(--border)" }}>
            <Link href="/privacy" className="text-[#FF9933] font-bold hover:underline">← Privacy Policy</Link>
            <Link href="/sitemap" className="text-[#FF9933] font-bold hover:underline">Site Map</Link>
            <Link href="/" className="text-[#FF9933] font-bold hover:underline">Back to Home</Link>
          </div>
        </div>
      </div>
    </div>
  );
}
